Switched most of echo to printf because it's a bash builtin. Enabled the test/*.sh scripts test against the libexec/bats file

diff --git a/libexec/bats-exec-test b/libexec/bats-exec-test
--- a/libexec/bats-exec-test
+++ b/libexec/bats-exec-test
@@ -17,10 +17,10 @@ fi
 
 BATS_TEST_FILENAME="$1"
 if [ -z "$BATS_TEST_FILENAME" ]; then
-  echo "usage: bats-exec <filename>" >&2
+  printf "usage: bats-exec <filename>\n" >&2
   exit 1
 elif [ ! -f "$BATS_TEST_FILENAME" ]; then
-  echo "bats: $BATS_TEST_FILENAME does not exist" >&2
+  printf "bats: $BATS_TEST_FILENAME does not exist\n" >&2
   exit 1
 else
   shift
@@ -40,7 +40,7 @@ load() {
   fi
 
   [ -f "$filename" ] || {
-    echo "bats: $filename does not exist" >&2
+    printf "bats: $filename does not exist\n" >&2
     exit 1
   }
 
@@ -82,7 +82,7 @@ skip() {
 bats_test_begin() {
   BATS_TEST_DESCRIPTION="$1"
   if [ -n "$BATS_EXTENDED_SYNTAX" ]; then
-    echo "begin $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
+    printf "begin $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION\n" >&3
   fi
   setup
 }
@@ -128,20 +128,20 @@ bats_print_stack_trace() {
     local lineno="$(bats_frame_lineno "$frame")"
 
     if [ $index -eq 1 ]; then
-      echo -n "# ("
+      printf -n "# (\n"
     else
-      echo -n "#  "
+      printf -n "#  \n"
     fi
 
     local fn="$(bats_frame_function "$frame")"
     if [ "$fn" != "$BATS_TEST_NAME" ]; then
-      echo -n "from function \`$fn' "
+      printf -n "from function \`$fn' \n"
     fi
 
     if [ $index -eq $count ]; then
-      echo "in test file $filename, line $lineno)"
+      printf "in test file $filename, line $lineno)\n"
     else
-      echo "in file $filename, line $lineno,"
+      printf "in file $filename, line $lineno,\n"
     fi
 
     let index+=1
@@ -156,26 +156,26 @@ bats_print_failed_command() {
 
   local failed_line="$(bats_extract_line "$filename" "$lineno")"
   local failed_command="$(bats_strip_string "$failed_line")"
-  echo -n "#   \`${failed_command}' "
+  printf -n "#   \`${failed_command}' \n"
 
   if [ $status -eq 1 ]; then
-    echo "failed"
+    printf "failed\n"
   else
-    echo "failed with status $status"
+    printf "failed with status $status\n"
   fi
 }
 
 bats_frame_lineno() {
   local frame="$1"
   local lineno="${frame%% *}"
-  echo "$lineno"
+  printf "$lineno\n"
 }
 
 bats_frame_function() {
   local frame="$1"
   local rest="${frame#* }"
   local fn="${rest%% *}"
-  echo "$fn"
+  printf "$fn\n"
 }
 
 bats_frame_filename() {
@@ -184,9 +184,9 @@ bats_frame_filename() {
   local filename="${rest#* }"
 
   if [ "$filename" = "$BATS_TEST_SOURCE" ]; then
-    echo "$BATS_TEST_FILENAME"
+    printf "$BATS_TEST_FILENAME\n"
   else
-    echo "$filename"
+    printf "$filename\n"
   fi
 }
 
@@ -198,7 +198,7 @@ bats_extract_line() {
 
 bats_strip_string() {
   local string="$1"
-  printf "%s" "$string" | sed -e "s/^[ "$'\t'"]*//" -e "s/[ "$'\t'"]*$//"
+  echo "%s" "$string" | sed -e "s/^[ "$'\t'"]*//" -e "s/[ "$'\t'"]*$//"
 }
 
 bats_trim_filename() {
@@ -206,9 +206,9 @@ bats_trim_filename() {
   local length="${#BATS_CWD}"
 
   if [ "${filename:0:length+1}" = "${BATS_CWD}/" ]; then
-    echo "${filename:length+1}"
+    printf "${filename:length+1}\n"
   else
-    echo "$filename"
+    printf "$filename\n"
   fi
 }
 
@@ -253,13 +253,13 @@ bats_exit_trap() {
   fi
 
   if [ -z "$BATS_TEST_COMPLETED" ] || [ -z "$BATS_TEARDOWN_COMPLETED" ]; then
-    echo "not ok $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
+    printf "not ok $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION\n" >&3
     bats_print_stack_trace "${BATS_ERROR_STACK_TRACE[@]}" >&3
     bats_print_failed_command "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" "$BATS_ERROR_STATUS" >&3
     sed -e "s/^/# /" < "$BATS_OUT" >&3
     status=1
   else
-    echo "ok ${BATS_TEST_NUMBER}${skipped} ${BATS_TEST_DESCRIPTION}" >&3
+    printf "ok ${BATS_TEST_NUMBER}${skipped} ${BATS_TEST_DESCRIPTION}\n" >&3
     status=0
   fi
 
@@ -268,7 +268,7 @@ bats_exit_trap() {
 }
 
 bats_perform_tests() {
-  echo "1..$#"
+  printf "1..$#\n"
   test_number=1
   status=0
   for test_name in "$@"; do
@@ -283,7 +283,7 @@ bats_perform_test() {
   if [ "$(type -t "$BATS_TEST_NAME" || true)" = "function" ]; then
     BATS_TEST_NUMBER="$2"
     if [ -z "$BATS_TEST_NUMBER" ]; then
-      echo "1..1"
+      printf "1..1\n"
       BATS_TEST_NUMBER="1"
     fi
 
@@ -296,7 +296,7 @@ bats_perform_test() {
     BATS_TEST_COMPLETED=1
 
   else
-    echo "bats: unknown test name \`$BATS_TEST_NAME'" >&2
+    printf "bats: unknown test name \`$BATS_TEST_NAME'\n" >&2
     exit 1
   fi
 }
@@ -313,7 +313,7 @@ BATS_OUT="${BATS_TMPNAME}.out"
 
 bats_preprocess_source() {
   BATS_TEST_SOURCE="${BATS_TMPNAME}.src"
-  { tr -d '\r' < "$BATS_TEST_FILENAME"; echo; } | bats-preprocess > "$BATS_TEST_SOURCE"
+  { tr -d '\r' < "$BATS_TEST_FILENAME"; printf "\n"; } | bats-preprocess > "$BATS_TEST_SOURCE"
   trap "bats_cleanup_preprocessed_source" err exit
   trap "bats_cleanup_preprocessed_source; exit 1" int
 }
@@ -336,7 +336,7 @@ if [ "$#" -eq 0 ]; then
   bats_evaluate_preprocessed_source
 
   if [ -n "$BATS_COUNT_ONLY" ]; then
-    echo "${#BATS_TEST_NAMES[@]}"
+    printf "${#BATS_TEST_NAMES[@]}\n"
   else
     bats_perform_tests "${BATS_TEST_NAMES[@]}"
   fi
