Make compatible with msysGit's Bash 3.1
* Old msysGit is still used by GitHub for Windows as of Oct 2015
* Replace [[ =~ ]] with parameter substitution using glob/extglob
* When tput is missing, assume 80-column terminal
* Don't use <()
* On Windows, use pass/fail symbols available in standard Console fonts
  - Test added for this new feature

diff --git a/libexec/bats-format-tap-stream b/libexec/bats-format-tap-stream
--- a/libexec/bats-format-tap-stream
+++ b/libexec/bats-format-tap-stream
@@ -1,13 +1,11 @@
 #!/usr/bin/env bash
 set -e
+shopt -s extglob
 
-# Just stream the TAP output (sans extended syntax) if tput is missing
-command -v tput >/dev/null || exec grep -v "^begin "
-
-header_pattern='[0-9]+\.\.[0-9]+'
+header_pattern='*+([0-9])..+([0-9])*'
 IFS= read -r header
 
-if [[ "$header" =~ $header_pattern ]]; then
+if [[ "$header" = $header_pattern ]]; then
   count="${header:3}"
   index=0
   failures=0
@@ -21,7 +19,7 @@ else
 fi
 
 update_screen_width() {
-  screen_width="$(tput cols)"
+  screen_width="$(type -t tput > /dev/null && tput cols || echo 80)"
   count_column_left=$(( $screen_width - $count_column_width ))
 }
 
@@ -37,9 +35,17 @@ begin() {
   go_to_column 1
 }
 
+if [[ $OSTYPE != *msys* ]]; then
+  PASS_SYMBOL='✓'
+  FAIL_SYMBOL='✗'
+else
+  PASS_SYMBOL='√'
+  FAIL_SYMBOL='×'
+fi
+
 pass() {
   go_to_column 0
-  printf " ✓ %s" "$name"
+  printf " $PASS_SYMBOL %s" "$name"
   advance
 }
 
@@ -54,7 +60,7 @@ skip() {
 fail() {
   go_to_column 0
   set_color 1 bold
-  printf " ✗ %s" "$name"
+  printf " $FAIL_SYMBOL %s" "$name"
   advance
 }
 
@@ -144,10 +150,10 @@ while IFS= read -r line; do
     flush
     ;;
   "ok "* )
-    skip_expr="ok $index # skip (\(([^)]*)\))?"
-    if [[ "$line" =~ $skip_expr ]]; then
+    skip_expr="ok $index # skip*"
+    if [[ "$line" = $skip_expr ]]; then
       let skipped+=1
-      buffer skip "${BASH_REMATCH[2]}"
+      buffer skip "${line//@(*\(|\)*)}"
     else
       buffer pass
     fi
